version: "2"
services:
  app:
    build: .
    links:
      - db
    ports:
      # for service api calls
      - "5000:5000"
      # port for debugger
      - "5678:5678"
    container_name: flask_app

  db:
    image: mysql:8.0.26
    ports:
      - "3300:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Wwt123456
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    container_name: mysql